export const FETCH_USERS_LOADING = "FETCH_USERS_LOADING";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_NOT_FOUND ="FETCH_USERS_NOT_FOUND";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USERS_LOADING_END ="FETCH_USERS_LOADING_END";

export const FETCH_USERS_CLEAR_LINKS_AND_PAGES = "FETCH_USERS_CLEAR_LINKS_AND_PAGES";
export const FETCH_USERS_RECORD_LINKS_AND_PAGES = "FETCH_USERS_RECORD_LINKS_AND_PAGES";
export const USERS_GET_DATA_OF_LOCAL_STORAGE = "USERS_GET_DATA_OF_LOCAL_STORAGE";
export const INCREMENT_REQUESTS = "INCREMENT_REQUESTS";
export const APPERANCE_NOTIFY = "APPERANCE_NOTIFY";
export const DISAPPERANCE_NOTIFY = "DISAPPERANCE_NOTIFY";